image: gradle:4.4.1-jdk8

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle :api:clean :api:build --configure-on-demand
  artifacts:
    name: GTS-${CI_COMMIT_REF_NAME}
    paths:
      - build/
  tags:
    - build
deploy:
  stage: deploy
  script:
    - gradle :api:publish -Pnexus-username=${NEXUS_USERNAME} -Pnexus-password=${NEXUS_PASSWORD} --configure-on-demand
